name: CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          TEST_NAME: Scarlett
        with:
          bootstrap: vendor/autoload.php
          php_extensions: "gd xdebug"
          configuration: phpunit.xml
          args: --coverage-cobertura
          coverage_cobertura: "coverage/cobertura.xml"
          version: "9.6.11"
      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
